spring:
  datasource:
    url: jdbc:h2:mem:salesReport
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: org.hibernate.dialect.H2Dialect

config:
  delimiter: รง
  delimiterItem: ","
  delimiterItemField: "-"
  allowed-extension: '.dat'
  file-extension-pattern: '*.dat'
  path: user.home
  path-in: /data/in
  path-out: /data/out
